<?php
/**
 * @var Laminas\View\Renderer\PhpRenderer $this
 * @var bool $isLogged
 */
?>
<?= $this->doctype() ?>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <?= $this->headTitle('Sistema de usuários')->setSeparator(' - ')->setAutoEscape(false) ?>

        <?= $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?= $this->headLink([
                                'rel' => 'shortcut icon',
                                'type' => 'image/vnd.microsoft.icon',
                                'href' => $this->basePath() . '/img/favicon.ico'
                            ])
            ->prependStylesheet($this->basePath('css/style.css'))
            ->prependStylesheet($this->basePath('css/bootstrap.min.css'))
?>

        <!-- Scripts -->
        <?= $this->headScript() ?>
    </head>
    <body>
        <nav class="navbar navbar-expand-md navbar-dark mb-4" role="navigation">
            <div class="container">
                <div class="collapse navbar-collapse justify-content-between" id="navbarSupportedContent">
                    <ul class="navbar-nav">
                        <li class="nav-item active">
                            <a class="nav-link" href="<?= $this->url('home') ?>">
                                Página Inicial
                            </a>
                        </li>

                        <?php if ($isLogged): ?>
                        <li class="nav-item active">
                            <a class="nav-link" href="<?= $this->url('user') ?>">
                                Usuários
                            </a>
                        </li>
                        <?php endif; ?>
                    </ul>

                    <ul class="navbar-nav">
                        <?php if (!$isLogged): ?>
                        <li class="nav-item active">
                            <a class="nav-link" href="<?= $this->url('login') ?>">
                                Entrar
                            </a>
                        </li>
                        <?php else: ?>
                        <li class="nav-item active">
                            <a class="nav-link" href="<?= $this->url('logout') ?>">
                                Sair
                            </a>
                        </li>
                        <?php endif; ?>
                    </ul>
                </div>
            </div>
        </nav>
        <div class="container">
            <?= $this->content ?>
            <hr>
        </div>
        <?= $this->inlineScript()
            ->prependFile($this->basePath('js/bootstrap.min.js'))
            ->prependFile($this->basePath('js/jquery-3.5.1.min.js')) ?>
    </body>
</html>
